image: maven:3.8.4-jdk-8

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn compile
    - echo "compile complete."
    
test:
  stage: test
  script:
    - echo "no test to perform"

